version: "4.8"  # 使用最高的版本号

services:
  alist:
    image: 'xhofe/alist:latest'
    container_name: alist
    volumes:
      - 'root/alist/data:/opt/alist/data'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped

  auto_symlink:
    image: shenxianmq/auto_symlink:latest
    container_name: auto_symlink
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/media:/home/media:rslave
      - /home/strm:/home/strm
      - /root/link/config:/app/config
    ports:
      - "8095:8095"
    user: "0:0"

  clouddrive2:
    image: cloudnas/clouddrive2
    container_name: clouddrive2
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    volumes:
      - /home/media:/media:shared
    devices:
      - /dev/fuse:/dev/fuse
    restart: unless-stopped
    pid: "host"
    privileged: true
    network_mode: "host"

  emby-server:
    image: amilys/embyserver:beta
    container_name: emby-server
    restart: always
    privileged: true
    ports:
      - "8096:8096"
    volumes:
      - /home/strm:/strm
      - /home/media:/home/media:rslave
      - /root/emby/config:/config

  medialinker:
    restart: always
    volumes:
      - '/root/mediaLinker/opt/:/opt/'
    environment:
      - AUTO_UPDATE=false
      - SERVER=emby
      - NGINX_PORT=8091
      - NGINX_SSL_PORT=8095
      - NGINX_LOG_LEVEL=error
    container_name: medialinker
    image: 'thsrite/medialinker:latest'
    network_mode: "host"

  nginx-proxy-manager: # 更名避免与其他服务冲突
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /root/nginx/data:/data
      - /root/nginx/letsencrypt:/etc/letsencrypt

  portainer:
    image: outlovecn/portainer-cn:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /root/portainer/dockerconfig/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
